apiVersion: v1
kind: ServiceAccount
metadata:
  name: skela-control
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: skela-control
rules:
  - apiGroups: [apps]
    resources: [deployments]
    resourceNames: [skela-control]
    verbs: [get]
  - apiGroups: [""]
    resources: [events]
    verbs: [list]
  - apiGroups: [""]
    resources: [pods/log]
    verbs: [get]
  - apiGroups: [metrics.k8s.io]
    resources: [pods]
    verbs: [get]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, create, update, patch]
  - apiGroups: [cert-manager.io]
    resources: [certificates]
    verbs: [get, create, patch, delete]
  - apiGroups: [""]
    resources: [secrets, configmaps, resourcequotas, persistentvolumeclaims, services, pods]
    verbs: [get, list, watch, create, patch, delete]
  - apiGroups: [""]
    resources: [serviceaccounts]
    verbs: [get]
  - apiGroups: [""]
    resources: [pods/exec]
    verbs: [get, create]
  - apiGroups: [apps]
    resources: [statefulsets]
    verbs: [get, list, watch, create, patch, delete]
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [get, list, watch, create, delete]
  - apiGroups: [skeladb.io]
    resources: [branches, branches/status]
    verbs: [get, list, watch, create, patch, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skela-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: skela-control
subjects:
  - kind: ServiceAccount
    name: skela-control
